### PR TITLE
1269509 - disable progress reporting.

### PR DESCRIPTION
**Pull request by jortel**
https://bugzilla.redhat.com/show_bug.cgi?id=1269509

### CODE REVIEW

**Comment by mccun934** [comment]
since this is a short-term fix I'm going to advocate we merge this against katello-2.2 instead of master. we can backport this into Satellite 6.1 and then work on a longer term fix in katello-agent/master

**Comment by mccun934** [comment]
going to close this in favor of:

https://github.com/Katello/katello-agent/pull/32

**Comment by jlsherrill** [comment]
@mccun934 i'm actually okay with going ahead and merging this to master.  Even if it is a short term fix, any reason not to?

**Comment by ehelms** [comment]
Can we get a proper Redmine issue and commit message update?

**Comment by jlsherrill** [comment]
@ehelms yes, we were just discussing that on IRC as well :)

**Comment by mccun934** [comment]
see https://github.com/Katello/katello-agent/pull/33

**Pull request closed without merging**
