### PR TITLE
Connect to localhost if we're a capsule

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by stbenjam** [comment]
Just opening this for a discussion, re: https://bugzilla.redhat.com/show_bug.cgi?id=1249890

We need to check that qdrouterd is running, and that the host IS a capsule.  Not sure the best way to do it, pythonically.

This seems to work, any ideas @jlsherrill @jortel ?

**Comment by jortel** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256



On 08/05/2015 09:09 AM, Stephen Benjamin wrote:
> This seems to work, any ideas @jlsherrill <https://github.com/jlsherrill> @jortel
> <https://github.com/jortel> ?
> 

Can you include a link to what "this" is?
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJVwkneAAoJEM9lW7UwFwZX/k8P/3clz0HpjMCMdfC0xaO748W+
grciymLCu/vZC7soaS11dshG75UmQRilrBELqwFFz8SSt4UlhlZocTpEMSnugjHn
5DvOaeYpTfebPne2BD7gftpZ6J9xoMLQpJtCbKPnPgbs/bxhlwNy0n1b5Ybo+jxt
1LK0Z1YUZ4RKhOSeIeZf12ay6TvXHtzVCoZjVYuwrsKt+NXEmFkNslnW9SUV7MKL
XW/FUXS8pCaPg7vbf78RatBWuVehe4U33Cg9blZAMJcTB+ZtLEvByTTNGZ3ItZb/
ZmOqODhDNUIUEbfhWV8+evCjxqJ6BX+3jhT4vqnhIMOiBXsfSLNIoIv01qg0nqbB
22dEAgyacz1kisopUal8ex95zRCIpZyJMM190cfPqNjDK5xnmFaGgLhkRCmO1IJS
DvQnrGGbBh3W3Cx0zsAFvOyD3hkz5JsA8P560gKqIs60WU/+wP6XsnOiVhVrlKvj
EKRbrgL1mDYtC5DMzSW1qh0o1xAQyl1B8OW/S0hi3tF0W/t/Hs5c33uyYIC9Lhrr
1LfnCKpOGbSIKL0h0ADTErvl7cNO035IsjrbJqKGi8WSuVQiFPopHAGIb/hSIIJ+
Y98jDBRnhM0Pq+O5+gCJCSi/RG9aW6I1BHo+fnmPwZqRvs/bPQfDxc0MBTi/M3OT
BgCq2yP/ZVWHrHM12iOu
=ZI0z
-----END PGP SIGNATURE-----

**Comment by stbenjam** [comment]
"This" as in this PR https://github.com/Katello/katello-agent/pull/30/files

**Comment by jlsherrill** [comment]
so the reason this fixes this particular bz is because the heartbeat is occuring between the qpid-routers?

So the same problem would occur with non-capsule clients?

**Comment by stbenjam** [comment]
Right, dispatch routers have heartbeat already so that connection between the capsule + katello is stable, but the goferd connection isn't.

It's far more likely that a Capsule and Katello have a firewall between them than the clients, so we wanted to get this in ASAP.  

goferd still needs to have heartbeat enabled itself for clients.  Reminds me of all the troubles I had with OSAD when I worked with Satellite 5.

Anyway, @jortel and I had a quick discussion on IRC earlier, and we can probably reduce this to only checking if a particular file exists (/etc/capsule-installer?).  Any thoughts on that?

**Comment by jlsherrill** [comment]
Gotcha.  I guess once gofer supports heartbeat (or we are no longer using gofer) we can get rid of this logic so hopefully its temporary. 

As for which method is better, I'm fairly torn and don't really like any solution :) 

Not sure if there are any implications about startup with the current solution (such as if goferd starts before qdrouterd).  So i'd say go with the simplest solution.  Checking for /etc/capsule-installer would be fine, but what about checking for /etc/qpid-dispatch/ instead?

**Comment by stbenjam** [comment]
> Gotcha. I guess once gofer supports heartbeat (or we are no longer using gofer) we can get rid of this logic so hopefully its temporary. As for which method is better, I'm fairly torn and don't really like any solution :) 

Qpid team initially raised this a long time ago, when I was working on configuring dispatcher. They said they preferred connecting to the closest broker. I get that, but  I'd rather just have the logic of "everybody connects to their RHSM server."  

Although, it does reduce a port requirement between the Satellite, and improves this heartbeat problem.

@jortel What's the effort to get the goferd to do heartbeat? Is in it scope for 6.1.2 zstream?

> Not sure if there are any implications about startup with the current solution (such as if goferd starts before qdrouterd). 

It could be, we have some time to figure that out.  We should probably include goferd in katello-service too, so it gets restarted in case of problems.

> Checking for /etc/capsule-installer would be fine, but what about checking for /etc/qpid-dispatch/ instead?

We're theoretically not the only user of dispatch router, and I figured that'd cause problems if anyone ever tried to manage a client running it

**Comment by jlsherrill** [comment]
```
We're theoretically not the only user of dispatch router, and I figured that'd cause problems if anyone ever tried to manage a client running it
```

That's an excellent point.  I guess checking for /etc/capsule-installer would be fine.

**Comment by jortel** [comment]
It's a 1-line change in gofer so the effort is minimal.  Although, we'd need to get the patch in PROTON-972 to be packaged and released.

**Comment by stbenjam** [comment]
Updated to just checking /etc/capsule-installer.

**Comment by ehelms** [comment]
@jlsherrill @jortel Please to re-review this patch

**Comment by jortel** [comment]
Looks fine to me but missing test coverage.

```
[jortel@localhost test]$ nosetests --cover-erase --with-coverage --cover-package=katello test_plugin.py
...............................
Name                          Stmts   Miss  Cover   Missing
-----------------------------------------------------------
katello                           0      0   100%   
katello.agent                     0      0   100%   
katello.agent.katelloplugin     179      6    97%   38-39, 169-171, 178-179
-----------------------------------------------------------
TOTAL                           179      6    97%   
----------------------------------------------------------------------
Ran 31 tests in 0.106s

OK
```

**Comment by stbenjam** [comment]
How do I test the `if os.path.isdir('/etc/capsule-installer'):` brach? In ruby I could stub os.path.isdir to return true there, but not sure how I can do that in Python, Google doesn't yield much help..

**Comment by jortel** [comment]
In python we use *mock* to patch things.
```
from mock import patch

class TestThings(TestCase):
    @patch('os.path.isdir')
    def test_something(self, isdir):
        isdir.return_value = True
        ...
```
Lots of examples here: https://github.com/jortel/katello-agent/blob/master/test/test_plugin.py

**Comment by ehelms** [comment]
@stbenjam planning to revisit this? Looks like it will need some updates based on changes around how if on a Foreman proxy are determined. If not, lets close this.

**Comment by stbenjam** [comment]
No intention to revisit this unless someone asks for it.

**Pull request closed without merging**
