### PR TITLE
Add Fedora 22

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by stbenjam** [comment]
Still need to setup all the right tags in Koji, I think I have an idea of how to do it, but I'm not 100% sure.  This isn't written or documented anywhere is it?

**Comment by ehelms** [comment]
Should be the same as the the fedora-20 or fedora-21 in the koji buildroot script except you don't clone anything when you setup the nightlies the first time I think -- @jlsherrill please confirm

**Comment by jlsherrill** [comment]
ACK

**Comment by jlsherrill** [comment]
@ehelms  thats correct basically this part:  

https://github.com/Katello/katello-misc/blob/master/rel-eng/koji_create_buildroots.sh#L111-L127

but instead of cloning from   katello-nightly-fedora21 to katello-VERSION-fedora21, you'd clone from 

katello-nightly-fedora21 to katello-nightly-fedora22

**Pull request merged**
