### PR TITLE
Fixes #17359 - Tracer yum plugin upload should look at all pkgs

### PR DESCRIPTION
**Pull request by sean797**
Were looking at all pkgs now, not just the ones in the most recent transaction

### CODE REVIEW

**Comment by sean797** [comment]
ping @jlsherrill this should fix https://github.com/Katello/katello-agent/pull/38#discussion_r87219963

**Comment by jlsherrill** [comment]
Testing this out, it seems to have the opposite effect for some reason:

1.  katello-tracer-upload reports mongodb
2.  yum upgrade tuned
3.  yum plugin only reports mongo
4.  katello-tracer-upload reports mongod and tuned

so now it seems to only be reporting things updated outside of yum, rather than only reporting things updated inside that yum transaction

**Comment by sean797** [comment]
Updated it again @jlsherrill, it looks like we cant just access the rpmdb as it isn't updated yet like I originally thought.

Looks to me working for me now anyway 👍

**Comment by sean797** [comment]
ping @jlsherrill I would love to get this in before 3.3 branching if you get a chance to test it before hand :)

**Comment by jlsherrill** [comment]
Thanks for the reminder @sean797 !  Seems to be working great now!  ACK

**Pull request merged**
